### ISSUE TITLE
WebFuzzer测试超10万后卡死白屏

### ISSUE THREAD

**Issue by YLXDXX** [yaklang/yakit#1427]
利用字典进行Web Fuzzer测试，数据量较小时，一切正常，当数据量比较大（如超过10万），就会出现卡死白屏的情况

下面是具体的报错信息：
```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/httpFuzzer.js:91:46)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:20:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at ClientReadableStreamImpl.push (node:internal/streams/readable:234:10)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client.js:341:24)
    at Object.onReceiveMessage (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:315:178)
    at /home/shui/.local/share/appimages/squashfs-root/resources/app.asar/node_modules/@grpc/grpc-js/build/src/resolving-call.js:166:39
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at ClientReadableStreamImpl.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/handlers/handleStreamWithContext.js:33:33)
    at ClientReadableStreamImpl.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:93682)
    at WebContents.send (node:electron/js2c/browser_init:2:79161)
    at BrowserWindow.<anonymous> (/home/shui/.local/share/appimages/squashfs-root/resources/app.asar/app/main/uiOperate/index.js:39:25)
    at BrowserWindow.emit (node:events:514:28)

```

使用版本：
![image](https://github.com/yaklang/yakit/assets/35033878/4e5ac7ff-e783-4400-8acb-1f2a2a557c95)

note：最新的版本，在Debian 12上跑不起来，启动白屏

**Comment by VillanCh** [comment]
这个错误多半是因为 OOM

10w 数据存在前端会导致内存占用过多被操作系统 Kill 渲染进程

在后续的一些版本中，在数据过大的时候会限制前端存储信息量，用数据库

**Comment by sevck** [comment]
+1  同样遇到这个问题，不知道有没有解决方案

应该是不是OOM，最开始我也以为内存不够system kill，昨晚更换了一个16G内存的，今天查看，仅占用3G+，fuzz仍然导致白屏

**Comment by VillanCh** [comment]
OOM不一定是系统不够用了，可能是渲染进程本身限制了，比如说Chrome可以限制他的子进程的内存。


这儿是有改进方案的，在有计划在数据量过大的情况下，直接在数据库中操作，可以期待之后的版本更新



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sevck ***@***.***&gt;
发送时间: 2024年3月6日 10:28
收件人: yaklang/yakit ***@***.***&gt;
抄送: v1ll4n ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yaklang/yakit] WebFuzzer测试超10万后卡死白屏 (Issue #1427)





 
+1  同样遇到这个问题，不知道有没有解决方案
 
应该是不是OOM，最开始我也以为内存不够system kill，昨晚更换了一个16G内存的，今天查看，仅占用3G+，fuzz仍然导致白屏

**Comment by WAY29** [comment]
已经在新版本中更新
